### ISSUE TITLE
License Issue with GPL

### ISSUE THREAD

**Issue by Elshid** [srmanikandasriram/ev3-ros#3]
I found some GPL'ed code in the Repository which is needed to compile the project (in the files src/ev3_demo.cpp, src/ev3_demo.h, ev3dev.h and ev3dev.cpp). However, the whole project is licensed under the MIT license. This is against the terms of the GPL, as pointed out here:  https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL. It is strictly necessary that the whole project is licensed under the (A)GPL.

This can only be resolved by the copyright holder of the repo, which is @srmanikandasriram.

**Comment by srmanikandasriram** [comment]
Thanks for bringing this to my notice. I have changed the license to GPL v2.
